Start type annotations
williballenthin/INDXParse pull request #37
Opened 2023-06-26 16:41 UTC by sldouglas-nist

Disclaimer: Participation by NIST in the creation of the documentation of mentioned software is not intended to imply a recommendation or endorsement by the National Institute of Standards and Technology, nor is it intended to imply that any specific software is necessarily the best available for the purpose.

The goal of this patch series is to improve type safety amongst core functions in the codebase and introduce support for static type review.

The first patch set enables a baseline state of mypy review where mypy raises no errors when reviewing the use of two INDXParse scripts.

The modifications made were tested with the following:

```bash
mypy list_mft.py MFTINDX.py
```

Status:
* Once the first patch should be accepted, `mypy` as called above passes.
* The patch removes some use of the `ord` function to handle the transition from python2 to python3.
* The patch successfully identifies and resolves one general bug form, pertaining to inconsistent use of the `datetime` module's functions.
* Each patch after the first continues to have `mypy` as called above pass.
* So far, the code has been type annotated for the `unpack_*`, `read_*`, and `dosdate` functions in `BinaryParser` with the exception of `unpack_filetime`.
   - The original intent of the function, with regards to returning `None` or `datetime` in the case of "null"-like input for `parse_filetime`, is unclear to us.
   - Dynamic code review is currently needed to understand expected behavior throughout the `INDXParse` codebase due to how `unpack_filetime` is set up to be called by `declare_field`.

Each patch log message describes its purpose.

2023-06-26 19:44 UTC, williballenthin commented
I'm a huge fan of these improvements! We've been using mypy in other projects recently and I wouldn't write any new Python without it. 

I'm happy to give this a close review and then merge. I'll also migrate over our Github Action config to run mypy against any new commits and PRs. Looking forward to the continued collaboration!

Are you all using this project? We'll I guess so if you'll invest some time in it. I'd be interested to hear what parts are useful, since I consider this such old code and don't often look at it. If you're continuing to use it, perhaps I can reinvigorate the project a bit. Feel free to email me (wilbal1087@gmail or wballenthin@google) if you'd prefer that medium. 

Thanks!

2023-06-27 09:48 UTC, williballenthin requested changes
these changes look really good!

using type annotations like this requires the user to be on python 3, i think 3.7+. we should update the project metadata to specify this. 

as noted inline, i think the `unpack_string` and `wstring` routines should return `str`. any objections?

2023-06-27 09:48 UTC, williballenthin commented on BinaryParser.py
> +    def unpack_string(self, offset: int, length: int) -> bytes:
i think this should return `str`, but i also suspect that this opens a whole can of worms. in any case, lets dive in!

2023-06-27 09:48 UTC, williballenthin commented on BinaryParser.py
> +    def unpack_string(self, offset: int, length: int) -> bytes:
is the "string" ASCII or utf-8 or...? should it accept the encoding as a kwarg parameter with a default of ASCII?

2023-06-27 09:48 UTC, williballenthin commented on BinaryParser.py
>          return self.unpack_binary(offset, length)
```suggestion
        return self.unpack_binary(offset, length).decode(encoding)
```

perhaps?

2023-06-27 09:48 UTC, williballenthin commented on BinaryParser.py
> +    def unpack_wstring(self, offset: int, length: int) -> bytes:
likewise, this should return a str.

2023-06-27 09:48 UTC, williballenthin commented on BinaryParser.py
>                                   parts[6], parts[7])
the alignment here is broken, but thats ok. i think we should introduce the black code formatter to handle things like this for us. i can do that after we merge this PR.

2023-06-28 19:35 UTC, williballenthin commented on BinaryParser.py
> +    def unpack_string(self, offset: int, length: int) -> bytes:
i still think these are the correct annotations but they've been deferred until future PRs.

2023-06-28 19:35 UTC, williballenthin commented on BinaryParser.py
>          return self.unpack_binary(offset, length)
deferred until later

2023-06-28 19:36 UTC, williballenthin commented on BinaryParser.py
> +    def unpack_wstring(self, offset: int, length: int) -> bytes:
deferred until future PR

2023-06-28 19:36 UTC, williballenthin approved these changes
changes look good. do you have any outstanding work @sldouglas-nist or are we good to merge?

2023-06-28 20:05 UTC, sldouglas-nist commented
> changes look good. do you have any outstanding work @sldouglas-nist or are we good to merge?

Hi @williballenthin, yes we are good to merge, thank you.

2023-06-28 20:10 UTC, merged