Transition INDXParse installation to using setup.cfg
williballenthin/INDXParse pull request #46
Opened 2023-07-13 20:16 UTC by ajnelson-nist

Commit 1 in this PR has a log message that documents the rationale.  Reorganizing the code base and changing the build system seemed to necessitate doing many things in one patch.  I'm happy to answer any questions.

2023-07-13 20:21 UTC, ajnelson-nist commented
@williballenthin : After one formatting hiccup (I usually handle `pre-commit` with a Make target; I forgot to set that up in a new temporary clone), I think this PR is ready to merge if you have no questions.

2023-07-14 12:55 UTC, williballenthin commented
Hey @ajnelson-nist 

Thanks for these changes. The code changes look solid, so those will be easy to accept.

Transitioning to use `setup.cfg` is fine, though ultimately the world is moving to `pyproject.toml` so perhaps we can do that before long. That doesn't block this PR, though.

I think we should discuss the licensing and headers that you've added in this PR. INDXParse is Apache 2.0 licensed and I would like to keep it that way. I'm not sure if it's possible to license software on a line-by-line basis, but in any case, I'm not comfortable doing it here. Would you please contribute the changes in accordance with the existing project license?

I'm also happy to accept a prominent acknowledgement that NIST contributed to the project in the README and CONTRIBUTORS files, but I don't want to include the full headers that you've proposed on the files that you've touched. If you want to update the headers, something like `# Alex Nelson contributed to this file during the course of their official duties at NIST.` is fine.

Happy to discuss further - let me know what you think.

2023-07-17 19:28 UTC, ajnelson-nist commented
Hi @williballenthin - I've condensed the inlined-header license text close to your suggestion.  Please let me know if there is anything else you would like to change.

2023-07-19 18:54 UTC, williballenthin requested changes
see inline comments, especially around licensing, which needs to be Apache 2.0.

2023-07-19 18:54 UTC, williballenthin commented on INDXParse/tree_mft.py
> +
these updated headers look great, thank you!

2023-07-19 18:54 UTC, williballenthin commented on README
> +Portions of this repository contributed by NIST are governed by the NIST Software Licensing Statement.  See THIRD_PARTY_LICENSES.md.
Which portions? How are users to know?

But maybe more importantly: INDXParse is licensed as Apache 2.0. Contributions to the repository need to be the same (unless *maybe* they can be separated into a dedicated `third_party` directory, such as a script or supporting data). Are you able to make contributions licensed as Apache 2.0?

If not, can we discuss alternatives and what they be?

2023-07-19 18:57 UTC, williballenthin commented on README
> +Portions of this repository contributed by NIST are governed by the NIST Software Licensing Statement.  See THIRD_PARTY_LICENSES.md.
IANAL, but if the contributions are not subject to copyright, then can they simply be relicensed to Apache 2.0?

2023-07-25 13:33 UTC, williballenthin approved these changes
thanks @ajnelson-nist for your patience during the discussion.  i really appreciate the effort and attention here. thank you!

2023-07-25 13:33 UTC, merged

2023-07-25 13:34 UTC, ajnelson-nist commented
Thank you, @williballenthin .  I appreciate your care on the matter too.