Add type annotations to `MFT.py` and `BinaryParser.py`
williballenthin/INDXParse pull request #64
Opened 2023-07-28 19:52 UTC by sldouglas-nist

The one patch's log message describes its purpose.

2023-07-29 06:03 UTC, williballenthin requested changes
some minor tweaks inline. 

thanks for the PR!

2023-07-29 06:03 UTC, williballenthin commented on indxparse/MFT.py
> +    def attributes(self) -> typing.Generator[Attribute, None, None]:
using `Iterator[Attribute]` is a bit simpler

2023-07-29 06:03 UTC, williballenthin commented on indxparse/MFT.py
> +    def is_directory(self) -> int:
should be bool

2023-07-29 06:03 UTC, williballenthin commented on indxparse/MFT.py
> +    def is_active(self) -> int:
bool

2023-07-31 14:44 UTC, sldouglas-nist commented on indxparse/MFT.py
> +    def attributes(self) -> typing.Generator[Attribute, None, None]:
Hi Willi, this was addressed in a recent patch.

2023-07-31 14:45 UTC, sldouglas-nist commented on indxparse/MFT.py
> +    def is_directory(self) -> int:
Hi Willi, these `bool` comments were addressed in a recent patch.

2023-07-31 18:00 UTC, williballenthin requested changes
one tweak, then ready to go

2023-08-01 14:01 UTC, sldouglas-nist commented on indxparse/MFT.py
> +    def record_generator(self, start_at=0) -> typing.Generator[MFTRecord, None, None]:
Hi Willi, this was addressed in a recent patch.

2023-08-01 14:01 UTC, williballenthin approved these changes
thank you @sldouglas-nist!

2023-08-01 14:02 UTC, merged